apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ssl-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: adrian.falke@gmail.com
    privateKeySecretRef:
      name: ssl-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
