apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-test-cert
  namespace: nginx-test
spec:
  secretName: nginx-test-tls-secret
  issuerRef:
    name: ssl-issuer
    kind: ClusterIssuer
  dnsNames:
    - nginx-test.brilliantbase.org
