apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-test-ingress
  namespace: nginx-test
spec:
  ingressClassName: nginx
  rules:
  - host: "${DOMAIN}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-test-svc 
            port:
              number: 80
  tls:
  - hosts:
  - ${DOMAIN}
    secretName: nginx-test-tls-secret
